# CrazyCore config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazyCore/src/config.yml
version: '8.7'
# wipe the players data file in "world/players" folder too.
wipePlayerFiles: true
# execute this commands when player is deleted 
# (Example: delete other plugins data too)
playerWipeCommands: 
- say $0$ has been wiped!
# block usage of >
disablePipes: false
# show [CrazyPlugin] chatheaders in front of every plugin message
showChatHeaders: true
# the servers default language
defaultLanguage: en_en
# the languages which are loaded on startup 
# (this languages will be updated when a plugin has been updated)
preloadedLanguages:
- de_de
- en_en
# the language selection for each player & console
players:
  console: en_en
