# CrazyCore config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazyCore/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazyCore/src/plugin.yml
# the chat header used ingame (this can only be changed, when server is shut down)
chatHeader: '&C[&ACrazyCore&C] &F'
# checks for updates, does not download it (true/false)
checkForUpdates: true
# removes the players data file in "world/players" folder too. (true/false)
# removes op and whitelist
wipePlayerWorldFiles: true
# a list of files which should be removed
# (Example: delete other plugins data too)
# wipePlayerFilePaths:
# - plugins/Plugin1/$0$.dat
# - plugins/Plugin2/players/$0$.yml
# - backup/world/players.dat
wipePlayerFilePaths: []
# execute this commands when player is deleted 
# (Example: delete other plugins data too)
# wipePlayerCommands:
# - say $0$ has been wiped!
# - permissions player removegroup $0$ user
# - money remove $0$
wipePlayerCommands: []
# removes player name from the banned list (true/false)
wipePlayerBans: false
# cancel deletion tasks for this player
protectedPlayers: []
# block usage of > (true/false)
disablePipes: false
# show [CrazyPlugin] chatheaders in front of every plugin message (true/false)
showChatHeaders: true
# when enabled every language selected by users will be loaded
loadUserLanguages: true
# the servers default language
defaultLanguage: en_en
# the languages which are loaded on startup 
# (this languages will be updated when a plugin has been updated)
preloadedLanguages:
- en_en
# - de_de
# - fr_fr
# - es_es
# the language selection for each player & console
players:
  console: en_en
