name: CrazyCore
main: de.st_ddt.crazycore.CrazyCore
author: ST-DDT
version: 9.0.7
description: >
            CrazyPlugin Core needed for all CrazyPlugins
commands:
  crazylist:
    description: Shows all enabled CrazyPlugins.
    usage: /<command>
  crazycore:
    description: Some further information and commands.
    usage: /<command> [Subcommands...]
  crazylanguage:
    description: Change languages
    usage: /<command> [Language]
    aliases: [language]
  crazypage:
    description: Scroll through pages.
    usage: /<command> [+/-/pagenumber]
    aliases: [page,cpage]
  crazypipe:
    description: Push data in pipe commands
    usage: /<command> <$PresetList>/<Arg1>, <Arg2>, ... [> PipeCommand]
    aliases: [pipe,cpipe]
permissions:
  crazy*.*:
    description: Access to all crazyplugin commands
    default: false
    children:
      crazylanguage.*: true
      crazypipe.use: true
  crazycore.*:
    description: Access to all commands
    default: false
    children:
      crazycore.list: true
      crazycore.infoplayer: true
      crazycore.deleteplayer: true
      crazylanguage.*: true
  crazycore.list:
    description: Allow showing all enabled CrazyPlugins
    default: op
  crazycore.infoplayer:
    description: Show all available information about a player
    default: op
  crazycore.deleteplayer:
    description: Delete all available information about a player
    default: op
    children:
      crazycore.deleteplayer.self: true
      crazycore.deleteplayer.other: true
  crazycore.deleteplayer.self:
    description: Delete all available information about you
    default: true
  crazycore.deleteplayer.other:
    description: Delete all available information about a player
    default: op
  crazylanguage.*:
    description: Access to all commands (Subsection language)
    default: op
    children:
      crazylanguage.advanced: true
  crazylanguage.advanced:
    description: Allow changing default languages or language reloads.
    default: op
  crazypipe.use:
    description: Allow usage of crazypipes.
    default: op