name: CrazyCore
main: de.st_ddt.crazycore.CrazyCore
author: ST-DDT
#C*=needed core version
version: C6.3
softdepend: [PermissionsBukkit]
description: >
            CrazyPlugin Core needed for all CrazyPlugins
commands:
  crazylist:
    description: Shows all enabled CrazyPlugins
    usage: /<command>
  crazylanguage:
    description: Change languages
    usage: /<command> [Language]
    aliases: [language]
  crazycore:
    description: Some further information and commands.
    usage: /<command> [Subcommands...]
permissions:
  crazy*.*:
    description: Access to all crazyplugin commands
    default: false 
  crazycore.*:
    description: Access to all commands
    default: false
    children:
      crazycore.list: true
      crazycore.language.advanced: true
  crazycore.list:
    description: Allow showing all enabled CrazyPlugins
    default: op
  crazycore.language.advanced:
    description: Allow changing default languages or language reloads.
    default: op