name: CrazyCore
main: de.st_ddt.crazycore.CrazyCore
author: ST-DDT
version: 10.0.2
website: http://dev.bukkit.org/server-mods/crazycore/
softdepend: [PermissionsEx,GroupManager,PermissionsBukkit]
description: >
            CrazyPlugin Core needed for all CrazyPlugins.
commands:
  crazylist:
    description: Shows all enabled CrazyPlugins.
    usage: /<command>
  crazycore:
    description: Some further information and commands.
    usage: /<command> [Subcommands...]
  crazylanguage:
    description: Change languages
    usage: /<command> [Language]
    aliases: [language]
  crazypage:
    description: Scroll through pages.
    usage: /<command> [+/-/pagenumber]
    aliases: [page,cpage]
  crazypipe:
    description: Push data in pipe commands
    usage: /<command> <$PresetList>/<Arg1>, <Arg2>, ... [> PipeCommand]
    aliases: [pipe,cpipe]
permissions:
  crazy*.*:
    description: Access to all crazyplugin commands
    default: false
    children:
      crazylanguage.advanced: true
      crazypipe.use: true
  crazycore.*:
    description: Access to all commands
    default: false
    children:
      crazycore.list: true
      crazycore.updatecheck: true
      crazycore.player.info: true
      crazycore.player.associates: true
      crazycore.player.ipsearch: true
      crazycore.player.delete: true
      crazycore.reload: true
      crazycore.save: true
      crazylanguage.advanced: true
      crazypipe.use: true
  crazycore.list:
    description: Allow showing all enabled CrazyPlugins.
    default: op
  crazycore.updatecheck:
    description: Allow checking for updates and get informed if updates are available.
    default: op
  crazycore.player.info:
    description: Allow displaying of all available information about a player (stored by CrazyPlugins).
    default: op
  crazycore.player.associates:
    description: Allow listing all known associates of a player (recursive) (stored by CrazyPlugins).
    default: op
  crazycore.player.ipsearch:
    description: Allow searching for players connected to this ip (stored by CrazyPlugins).
    default: op
  crazycore.player.delete:
    description: Allow deleting a player and all his stored information (CrazyPlugins+Commands).
    default: op
  crazycore.reload:
    description: Allow reload plugin.
    default: op
  crazycore.save:
    description: Allow saving plugin.
    default: op
  crazylanguage.advanced:
    description: Allow changing default languages or language reloads.
    default: op
  crazypipe.use:
    description: Allow usage of crazypipes.
    default: op