name: CrazyCore
main: de.st_ddt.crazycore.CrazyCore
author: ST-DDT
#C*=needed core version
version: C8.1.2
softdepend: [PermissionsBukkit]
description: >
            CrazyPlugin Core needed for all CrazyPlugins
commands:
  crazylist:
    description: Shows all enabled CrazyPlugins
    usage: /<command>
  crazycore:
    description: Some further information and commands.
    usage: /<command> [Subcommands...]
  crazylanguage:
    description: Change languages
    usage: /<command> [Language]
    aliases: [language]
permissions:
  crazy*.*:
    description: Access to all crazyplugin commands
    default: false 
  crazycore.*:
    description: Access to all commands
    default: false
    children:
      crazycore.list: true
      crazylanguage.*: true
  crazycore.list:
    description: Allow showing all enabled CrazyPlugins
    default: op
  crazylanguage.*:
    description: Access to all commands (Subsection language)
    default: op
    children:
      crazylanguage.advanced: true
  crazylanguage.advanced:
    description: Allow changing default languages or language reloads.
    default: op